const app=document.getElementById("app"),TXT=SH_TEXT,M=SH_MISSIONS,B=SH_BADGES;
let state=SHStorage.load();
const t=k=>TXT[state.lang||"ms"][k],save=()=>SHStorage.save(state);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const officialScore=n=>SHStorage.getOfficialScore(state,n),practiceScore=n=>SHStorage.getPracticeScore(state,n);
const officialScores=()=>Array.from({length:10},(_,i)=>officialScore(i+1));
const pass=()=>officialScores().filter((v,i)=>v>=60&&SHStorage.isOfficialLocked(state,i+1)).length;
const avg=()=>{const v=officialScores().filter(x=>x>=60);return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0};
const level=()=>1+Math.floor((state.xp||0)/500),rank=()=>level()>=10?t("hero"):level()>=7?t("specialist"):level()>=4?t("technician"):t("trainee"),progress=()=>Math.round(pass()/10*100);

function renderLanguage(){app.innerHTML=`<section class="center"><div class="card hero"><div class="logo">🖥️</div><h1>SERVER HERO™</h1><p>V5 C05</p><h2>${TXT.ms.choose}<br><small>${TXT.en.choose}</small></h2><div class="lang-grid"><button onclick="choose('ms')">🇲🇾<b>${TXT.ms.bm}</b></button><button class="en" onclick="choose('en')">🇬🇧<b>${TXT.en.en}</b></button></div></div></section>`;}
function choose(l){state.lang=l;save();state.student?renderDashboard():renderLogin()}
function renderLogin(){const a=["👨‍💻","👩‍💻","🛡️","⚙️","🧠","🚀"];app.innerHTML=`<section class="center"><div class="card login"><h1>SERVER HERO™</h1><h2>${t("login")}</h2><label>${t("name")}</label><input id="name"><label>${t("id")}</label><input id="id"><label>Kelas</label><input id="className" placeholder="Contoh: DKA3A"><h3>${t("avatar")}</h3><div class="avatars">${a.map((x,i)=>`<button class="${i===0?"active":""}" data-a="${x}" onclick="pick(this)">${x}</button>`).join("")}</div><button class="primary wide" onclick="saveLogin()">${t("enter")}</button></div></section>`;}
function pick(b){document.querySelectorAll(".avatars button").forEach(x=>x.classList.remove("active"));b.classList.add("active")}
function saveLogin(){const name=document.getElementById("name").value.trim(),id=document.getElementById("id").value.trim(),className=document.getElementById("className").value.trim();if(!name||!id){alert(t("required"));return}SHStorage.activateStudent(state,{name,id,className,avatar:document.querySelector(".avatars .active")?.dataset.a||"👨‍💻"});state.xp=Math.max(state.xp||0,50);if(!state.badges.includes("first-login"))state.badges.push("first-login");save();renderDashboard();}

function renderDashboard(){
 const courseComplete=pass()===10, unlocked=Math.min(Number(state.unlockedKP||state.unlocked)||1,10),next=courseComplete?null:(M.find(x=>x.id===unlocked)||M[0]);
 app.innerHTML=`<div class="shell ${state.projector?"projector":""}"><header><div class="student"><span>${state.student.avatar}</span><div><b>${esc(state.student.name)}</b><small>${esc(state.student.id)}${state.student.className?` · ${esc(state.student.className)}`:""}</small></div></div><div class="tools"><button onclick="renderLanguage()">🌍 ${t("language")}</button><button onclick="toggleProjector()">📽️ ${t("projector")}</button><button onclick="toggleFullscreen()">⛶ ${t("fullscreen")}</button><button onclick="changeProfile()">👤 ${t("change")}</button><button class="warn" onclick="resetProgress()">↻ ${t("reset")}</button><button class="danger" onclick="logout()">⏻ ${t("logout")}</button></div></header>
 <section class="dash-grid"><article class="card profile"><div class="avatar">${state.student.avatar}</div><h2>${esc(state.student.name)}</h2><p>${esc(state.student.id)}</p><div class="rank">⭐ ${rank()}</div><div class="bar"><i style="width:${progress()}%"></i></div><strong>${progress()}%</strong></article>
 <article class="card overview"><h1>${t("dashboard")}</h1><p>${courseComplete?"KURSUS TAMAT — Tahniah, Server Hero!":"KT dalam sistem ialah latihan. Hanya markah yang dimasukkan oleh guru menjadi markah rasmi."}</p><div class="stats"><article><span>${t("progress")}</span><b>${progress()}%</b></article><article><span>Purata Rasmi</span><b>${avg()}%</b></article><article><span>${t("level")}</span><b>${level()}</b></article><article><span>${t("xp")}</span><b>${state.xp}</b></article><article><span>🪙 ${t("coins")}</span><b>${state.coins||0}</b></article></div><div class="next"><div><small>${t("next")}</small><h3>${courseComplete?"🏆 SEMUA 10 MISI SELESAI":`KP${String(next.id).padStart(2,"0")} · ${next[state.lang]}`}</h3></div>${courseComplete?"":`<button onclick="openMission(${next.id})">${t("start")} →</button>`}</div>
 <div class="v5-actions"><button onclick="openTeacherMode()">👨‍🏫 Rekod Markah KT</button><button onclick="SHStorage.exportCSV(state)">📊 Export CSV</button><button onclick="SHStorage.exportJSON(state)">💾 Backup JSON</button></div></article></section>
 <section class="card missions"><h2>${t("missionMap")}</h2><div class="mission-list">${M.map((m,i)=>{const open=m.id<=unlocked,done=state.completedKP.includes(m.id),p=practiceScore(m.id),o=officialScore(m.id),locked=SHStorage.isOfficialLocked(state,m.id);return `<article class="${open?"open":"locked"} ${done?"done":""}"><div class="num">${done?"✓":String(m.id).padStart(2,"0")}</div><div class="icon">${m.icon}</div><div><small>KP${String(m.id).padStart(2,"0")}</small><h3>${m[state.lang]}</h3><div class="score-pills"><em>Latihan: ${p?p+"%":"—"}</em><em class="${locked?"official":"pending"}">Rasmi: ${o?o+"%":"—"} ${locked?"🔒":""}</em></div></div><span>${locked?"TERAMPIL":open?t("available"):t("locked")}</span><button ${open?"":"disabled"} onclick="openMission(${m.id})">${t("start")}</button></article>${i<M.length-1?'<div class="line"></div>':""}`}).join("")}</div></section>
 <section class="bottom"><article class="card badges"><h2>${t("badges")}</h2><div class="badge-grid">${B.map(b=>`<article class="${state.badges.includes(b.id)?"earned":"locked"}"><span>${b.icon}</span><small>${b[state.lang]}</small></article>`).join("")}</div></article><article class="card achievements"><h2>${t("achievements")}</h2><div><span>📘</span><b>${state.completedKP.length}/10 KP</b></div><div><span>🔒</span><b>${pass()}/10 KT Rasmi</b></div><div><span>🏆</span><b>${rank()}</b></div></article></section></div>`;
}

function openTeacherMode(){
 const pin=prompt("Masukkan PIN Mod Guru:");if(pin!==SHStorage.teacherPin){alert("PIN Mod Guru tidak sah.");return}
 const rec=SHStorage.getOfficialRecord(state,state.student.id)||{scores:{},locked:{}};
 app.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" id="teacherModal"><section class="teacher-modal"><button class="modal-close" onclick="closeTeacherMode()">×</button><h2>👨‍🏫 Rekod Markah Rasmi KT</h2><p>Markah bawah 60% masih boleh diubah. Apabila mencapai 60% atau lebih, markah menjadi rasmi dan terus dikunci.</p><div class="teacher-grid"><label>Nama Pelajar<input id="tmName" value="${esc(state.student.name)}"></label><label>ID Pelajar<input id="tmId" value="${esc(state.student.id)}"></label><label>Kelas<input id="tmClass" value="${esc(state.student.className||"")}"></label><label>Pilih KT<select id="tmKT" onchange="refreshTeacherEntry()">${Array.from({length:10},(_,i)=>`<option value="${i+1}">KT${String(i+1).padStart(2,"0")}</option>`).join("")}</select></label><label>Markah Rasmi<input id="tmScore" type="number" min="0" max="100" placeholder="0–100"></label><label>Catatan<input id="tmNote" placeholder="Pilihan"></label></div><div id="tmStatus" class="teacher-status"></div><div class="teacher-actions"><button class="primary" id="tmSave" onclick="saveOfficialMark()">💾 Simpan / Kemas Kini</button><button class="danger" onclick="adminUnlockMark()">🛡️ Admin Buka Kunci</button><button onclick="closeTeacherMode()">Tutup</button></div></section></div>`);refreshTeacherEntry();
}
function refreshTeacherEntry(){const id=document.getElementById("tmId")?.value||state.student.id,kt=Number(document.getElementById("tmKT")?.value||1),rec=SHStorage.getOfficialRecord(state,id),key=`kt${String(kt).padStart(2,"0")}`,score=Number(rec?.scores?.[key]||0),locked=Boolean(rec?.locked?.[key]);document.getElementById("tmScore").value=score||"";document.getElementById("tmScore").disabled=locked;document.getElementById("tmSave").disabled=locked;document.getElementById("tmStatus").innerHTML=locked?`<strong class="locked-mark">🔒 RASMI · TERAMPIL · ${score}%</strong><small>Markah ini tidak boleh diubah melalui Mod Guru.</small>`:score?`<strong class="pending-mark">BELUM RASMI · ${score}%</strong><small>Masih boleh dikemas kini sehingga mencapai 60%.</small>`:`<strong>BELUM DINILAI</strong>`;}
function saveOfficialMark(){const student={name:document.getElementById("tmName").value.trim(),id:document.getElementById("tmId").value.trim(),className:document.getElementById("tmClass").value.trim()},kt=Number(document.getElementById("tmKT").value),score=document.getElementById("tmScore").value,note=document.getElementById("tmNote").value;const result=SHStorage.saveOfficialResult(state,student,kt,score,note);alert(result.message);state=SHStorage.load();if(result.ok&&result.locked){closeTeacherMode();renderDashboard()}else refreshTeacherEntry();}
function adminUnlockMark(){const id=document.getElementById("tmId").value.trim(),kt=Number(document.getElementById("tmKT").value),pin=prompt("Masukkan PIN Admin untuk membuka kunci markah:");const result=SHStorage.adminUnlockOfficial(state,id,kt,pin);alert(result.message);state=SHStorage.load();refreshTeacherEntry();}
function closeTeacherMode(){document.getElementById("teacherModal")?.remove();}
function openMission(id){const unlocked=Math.min(Number(state.unlockedKP||state.unlocked)||1,10);if(id>=1&&id<=10&&id<=unlocked){window.location.href=`kp/kp${String(id).padStart(2,"0")}.html`;return}alert("KP ini masih dikunci. Markah rasmi KT sebelumnya mesti mencapai 60%.");}
function toggleProjector(){state.projector=!state.projector;save();renderDashboard()}
function toggleFullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()}
function changeProfile(){state.student=null;save();renderLogin()}
function logout(){if(confirm(t("confirmLogout"))){state.student=null;save();renderLanguage()}}
function resetProgress(){if(confirm("Reset data latihan pada peranti ini? Markah rasmi yang dikunci akan dikekalkan.")){state.practiceScores={};state.practiceBestScores={};state.practiceAttempts={};state.completedKP=[];state.xp=50;state.coins=0;state.badges=["first-login"];save();renderDashboard()}}
state.lang?(state.student?renderDashboard():renderLogin()):renderLanguage();
